CPSGrader::transducer
const trace_data* CPSGrader::transducer::trace_data_ptr
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
map<string, double> CPSGrader::transducer::param_map
map<string, int> CPSGrader::transducer::signal_map
double CPSGrader::transducer::start_time
Referenced by CPSGrader::not_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::stl_atom::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, CPSGrader::stl_atom::causation_opt_upper.
double CPSGrader::transducer::end_time
Referenced by CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::stl_atom::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, CPSGrader::stl_atom::causation_opt_upper.
Signal CPSGrader::transducer::z
Referenced by mexFunction.
Signal CPSGrader::transducer::z_up
Referenced by CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, mexFunction.
Signal CPSGrader::transducer::z_low
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, mexFunction.
Signal CPSGrader::transducer::cau
Signal CPSGrader::transducer::cau_up
Referenced by CPSGrader::not_transducer::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, CPSGrader::stl_atom::causation_opt_upper.
Signal CPSGrader::transducer::cau_low
Referenced by CPSGrader::not_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::stl_atom::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper.
double CPSGrader::transducer::duration
long int CPSGrader::transducer::check
CPSGrader::transducer::transducer()
virtual transducer* CPSGrader::transducer::clone() const =0
Referenced by CPSGrader::not_transducer::clone, CPSGrader::and_transducer::clone, CPSGrader::or_transducer::clone, CPSGrader::implies_transducer::clone, CPSGrader::ev_transducer::clone, CPSGrader::alw_transducer::clone, CPSGrader::until_transducer::clone, CPSGrader::stl_atom::clone, mexFunction.
virtual CPSGrader::transducer::~transducer()
virtual void CPSGrader::transducer::init_horizon()=0
void CPSGrader::transducer::set_horizon(double s, double e)
Referenced by mexFunction.
virtual void CPSGrader::transducer::set_duration()
Referenced by mexFunction.
virtual void CPSGrader::transducer::set_trace_data_ptr(const trace_data &trace)
Referenced by mexFunction.
virtual double CPSGrader::transducer::causation_opt_upper()
Referenced by CPSGrader::not_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, mexFunction.
virtual double CPSGrader::transducer::causation_opt_lower()
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper, mexFunction.
virtual int CPSGrader::transducer::get_index()
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
virtual double CPSGrader::transducer::get_value()
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
bool CPSGrader::transducer::double_equals(double a, double b)
bool CPSGrader::transducer::double_greater(double a, double b)
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
bool CPSGrader::transducer::double_less(double a, double b)
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
bool CPSGrader::transducer::double_ge(double a, double b)
bool CPSGrader::transducer::double_le(double a, double b)
virtual double CPSGrader::transducer::compute_robustness()=0
virtual double CPSGrader::transducer::compute_lower_rob()
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, mexFunction.
virtual double CPSGrader::transducer::compute_upper_rob()
Referenced by CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, mexFunction.
virtual double CPSGrader::transducer::update_robustness()
virtual double CPSGrader::transducer::update_lower_rob()
virtual double CPSGrader::transducer::update_upper_rob()
virtual double CPSGrader::transducer::get_end_complete()
virtual double CPSGrader::transducer::get_end_complete_low()
virtual double CPSGrader::transducer::get_end_complete_up()
virtual void CPSGrader::transducer::print() const =0
virtual void CPSGrader::transducer::print(ostream &os) const =0
void CPSGrader::transducer::print_trace()
bool CPSGrader::transducer::get_param(const string &, double &)
Referenced by CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper.
Signal CPSGrader::transducer::get_signal() const