CPSGrader::Parser
@0
typedef location CPSGrader::Parser::location_type
Symbol locations.
typedef token::yytokentype CPSGrader::Parser::token_type
(External) token type, as returned by yylex.
typedef int CPSGrader::Parser::symbol_number_type
Symbol type: an internal symbol number.
typedef unsigned char CPSGrader::Parser::token_number_type
Internal symbol number for tokens (subsumed by symbol_number_type).
typedef basic_symbol<by_type> CPSGrader::Parser::symbol_type
"External" symbols: returned by the scanner.
typedef int CPSGrader::Parser::debug_level_type
Type for debugging levels.
@1
typedef int CPSGrader::Parser::state_type
State numbers.
typedef stack<stack_symbol_type> CPSGrader::Parser::stack_type
Stack type.
const signed char CPSGrader::Parser::yypact_ninf_
const signed char CPSGrader::Parser::yytable_ninf_
const signed char CPSGrader::Parser::yypact_[]
const unsigned char CPSGrader::Parser::yydefact_[]
const signed char CPSGrader::Parser::yypgoto_[]
const signed char CPSGrader::Parser::yydefgoto_[]
const unsigned char CPSGrader::Parser::yytable_[]
const short int CPSGrader::Parser::yycheck_[]
const unsigned char CPSGrader::Parser::yystos_[]
const unsigned char CPSGrader::Parser::yyr1_[]
const unsigned char CPSGrader::Parser::yyr2_[]
const char *const CPSGrader::Parser::yytname_[]
For a symbol, its name in clear.
const unsigned short int CPSGrader::Parser::yyrline_[][]
int CPSGrader::Parser::yydebug_
std::ostream* CPSGrader::Parser::yycdebug_
stack_type CPSGrader::Parser::yystack_
The stack.
class STLDriver& CPSGrader::Parser::driver
CPSGrader::Parser::Parser(class STLDriver &driver_yyarg)
Build a parser object.
CPSGrader::Parser::~Parser()
int CPSGrader::Parser::parse()
Parse. 0 iff parsing succeeded.
References CPSGrader::STLDriver::add_stl_test, CPSGrader::STLDriver::add_trace_test, CPSGrader::Parser::basic_symbol< Base >::clear, CPSGrader::transducer::clone, CPSGrader::STLDriver::data, CPSGrader::Parser::basic_symbol< Base >::empty, error, CPSGrader::STLDriver::formula_map, CPSGrader::Parser::basic_symbol< Base >::location, CPSGrader::STLDriver::param_map, s_to_d, CPSGrader::STLDriver::signal_map, CPSGrader::STLDriver::streamname, CPSGrader::Parser::basic_symbol< Base >::value, YY_NULLPTR, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYCDEBUG, YYERROR, yylex, YYLLOC_DEFAULT.
Referenced by CPSGrader::STLDriver::parse_stream.
std::ostream& CPSGrader::Parser::debug_stream() const YY_ATTRIBUTE_PURE
The current debugging stream.
void CPSGrader::Parser::set_debug_stream(std::ostream &)
Set the current debugging stream.
debug_level_type CPSGrader::Parser::debug_level() const YY_ATTRIBUTE_PURE
The current debugging level.
void CPSGrader::Parser::set_debug_level(debug_level_type l)
Set the current debugging level.
Referenced by CPSGrader::STLDriver::parse_stream.
void CPSGrader::Parser::error(const location_type &loc, const std::string &msg)
Report a syntax error. loc where the syntax error is found. msg a description of the syntax error.
Referenced by error, parse.
void CPSGrader::Parser::error(const syntax_error &err)
Report a syntax error.
References error, CPSGrader::Parser::syntax_error::location.
CPSGrader::Parser::Parser(const Parser &)
This class is not copyable.
Parser& CPSGrader::Parser::operator=(const Parser &)
std::string CPSGrader::Parser::yysyntax_error_(state_type yystate, const symbol_type &yyla) const
Generate an error message. yystate the state where the error occurred. yyla the lookahead token.
Parser::state_type CPSGrader::Parser::yy_lr_goto_state_(state_type yystate, int yysym)
Compute post-reduction state. yystate the current state yysym the nonterminal to push on the stack
virtual void CPSGrader::Parser::yy_reduce_print_(int r)
Report on the debug stream that the rule r is going to be reduced.
virtual void CPSGrader::Parser::yystack_print_()
Print the state stack on the debug stream.
void CPSGrader::Parser::yy_print_(std::ostream &yyo, const basic_symbol< Base > &yysym) const
Display a symbol type, value and location.
yyo The output stream. yysym The symbol.
void CPSGrader::Parser::yy_destroy_(const char *yymsg, basic_symbol< Base > &yysym) const
Reclaim the memory associated to a symbol.
yymsg Why this token is reclaimed. If null, print nothing. yysym The symbol.
void CPSGrader::Parser::yypush_(const char *m, stack_symbol_type &s)
Push a new state on the stack. m a debug message to display if null, no trace is output. s the symbol the contents of s.value is stolen.
void CPSGrader::Parser::yypush_(const char *m, state_type s, symbol_type &sym)
Push a new look ahead token on the state on the stack. m a debug message to display if null, no trace is output. s the state sym the symbol (for its value and location). the contents of s.value is stolen.
void CPSGrader::Parser::yypop_(unsigned int n=1)
Pop n symbols the three stacks.
bool CPSGrader::Parser::yy_pact_value_is_default_(int yyvalue)
Whether the given yypact_ value indicates a defaulted state. yyvalue the value to check
bool CPSGrader::Parser::yy_table_value_is_error_(int yyvalue)
Whether the given yytable_ value indicates a syntax error. yyvalue the value to check
Parser::token_number_type CPSGrader::Parser::yytranslate_(int t)
Convert a scanner token number t to a symbol number.
std::string CPSGrader::Parser::yytnamerr_(const char *n)
Convert the symbol name n to a form suitable for a diagnostic.