CPSGrader::Signal
double CPSGrader::Signal::BigM
double CPSGrader::Signal::beginTime
Referenced by appendSample, reset, resize, shift, Signal.
double CPSGrader::Signal::endTime
Referenced by addLastSample, appendSample, CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, reset, resize, shift, Signal, simplify.
CPSGrader::Signal::Signal()
CPSGrader::Signal::Signal(double, double, int)
References beginTime, endTime.
CPSGrader::Signal::Signal(double *, double *, int)
References beginTime, endTime.
void CPSGrader::Signal::appendSample(double, double)
References beginTime, endTime.
Referenced by appendSignal, CPSGrader::not_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::stl_atom::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper, CPSGrader::stl_atom::causation_opt_upper.
void CPSGrader::Signal::appendSample(double, double, double)
References beginTime, endTime.
void CPSGrader::Signal::appendSignal(Signal)
References appendSample.
void CPSGrader::Signal::simplify()
References endTime.
void CPSGrader::Signal::resize(double, double, double)
References beginTime, CPSGrader::Sample::derivative, endTime, CPSGrader::Sample::valueAt.
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper.
void CPSGrader::Signal::shift(double)
References beginTime, endTime.
void CPSGrader::Signal::addLastSample()
References endTime.
void CPSGrader::Signal::removeInf()
References BOTTOM, TOP.
void CPSGrader::Signal::reset()
References beginTime, endTime.
Referenced by CPSGrader::stl_atom::causation_opt_lower, CPSGrader::stl_atom::causation_opt_upper.
double CPSGrader::Signal::get_value(double, int)
References BOTTOM, TOP.
void CPSGrader::Signal::dumpFile(const string filename) const
void CPSGrader::Signal::compute_not(const Signal &)
Signal becomes neg of signal argument.
Robustness computation functions - all these methods first clear content
Referenced by CPSGrader::not_transducer::causation_opt_lower, CPSGrader::not_transducer::causation_opt_upper.
void CPSGrader::Signal::compute_and(const Signal &, const Signal &)
Signal becomes conjunction (min) of the two arguments.
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::and_transducer::causation_opt_upper, CPSGrader::or_transducer::causation_opt_upper.
void CPSGrader::Signal::compute_or(const Signal &, const Signal &)
Signal becomes disjunction (max) of the two arguments.
Referenced by CPSGrader::and_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_lower, CPSGrader::or_transducer::causation_opt_upper, CPSGrader::ev_transducer::causation_opt_upper.
void CPSGrader::Signal::compute_implies(const Signal &, const Signal &)
Signal becomes implication (max of not x and y) of the two arguments.
void CPSGrader::Signal::compute_eventually(const Signal &)
Signal becomes robust eventually of argument.
void CPSGrader::Signal::compute_bounded_eventually(const Signal &, double)
ev_[0, a)
void CPSGrader::Signal::compute_timed_eventually(const Signal &, double, double)
ev_[a,b]
Referenced by CPSGrader::ev_transducer::causation_opt_lower, CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_upper.
void CPSGrader::Signal::compute_globally(const Signal &)
Signal becomes robust globally of argument.
void CPSGrader::Signal::compute_bounded_globally(const Signal &, double)
alw_[0, a)
void CPSGrader::Signal::compute_timed_globally(const Signal &, double, double)
alw_[a,b]
Referenced by CPSGrader::alw_transducer::causation_opt_lower, CPSGrader::ev_transducer::causation_opt_upper, CPSGrader::alw_transducer::causation_opt_upper.
void CPSGrader::Signal::compute_until(const Signal &, const Signal &)
Signal becomes robust untimed until.
void CPSGrader::Signal::compute_timed_until(const Signal &, const Signal &, double, double)
until_[a,b]
void CPSGrader::Signal::compute_plateau_max(const Signal &, double)
computes max lemire window of size a of argument signal
TODO Auxiliary routines (should be privatized probably)
void CPSGrader::Signal::compute_plateau_min(const Signal &, double)
std::ostream& operator<<(std::ostream &, const Signal &)