CPSGrader::STLDriver
bool CPSGrader::STLDriver::trace_scanning
DATA.
enable debug output in the flex scanner
Referenced by main, parse_stream.
bool CPSGrader::STLDriver::trace_parsing
enable debug output in the bison parser
Referenced by main, parse_stream.
std::string CPSGrader::STLDriver::streamname
stream name (file or input stream) used for error messages.
Referenced by CPSGrader::Parser::parse, parse_stream.
map<string, double> CPSGrader::STLDriver::param_map
parameters in formulas
Referenced by clear, CPSGrader::Parser::parse, print.
map<string, int> CPSGrader::STLDriver::signal_map
signals in formulas
Referenced by CPSGrader::Parser::parse.
map<string, transducer*> CPSGrader::STLDriver::formula_map
formulas defined by the driver
Referenced by clear, dump, mdlUpdate, mexFunction, CPSGrader::Parser::parse, print, test_formula.
map<string, stl_test> CPSGrader::STLDriver::stl_test_map
tests (sets of formulas)
Referenced by add_stl_test, clear.
trace_data CPSGrader::STLDriver::data
data array - time is first column
Referenced by dump, dump_trace_file, mdlUpdate, mexFunction, CPSGrader::Parser::parse, print_trace, read_trace_file, run_tests, STLDriver, test_formula.
deque<trace_test> CPSGrader::STLDriver::trace_test_queue
Referenced by add_stl_test, add_trace_test, clear, get_next_formula, get_next_stl_test, get_next_trace_test, get_next_trace_test_env, pop_next_trace_test, print, run_tests, trace_test_queue_empty.
string CPSGrader::STLDriver::report
Referenced by clear, main, run_tests.
string CPSGrader::STLDriver::test_log
Referenced by clear, dump_test_log_file, main, run_tests.
int CPSGrader::STLDriver::nb_test_pos
Referenced by clear, dump_test_log_file, run_tests.
int CPSGrader::STLDriver::nb_test_total
Referenced by add_stl_test, clear, dump_test_log_file.
bool CPSGrader::STLDriver::error_flag
Referenced by clear, run_tests.
class Scanner* CPSGrader::STLDriver::lexer
Pointer to the current lexer instance, this is used to connect the parser to the scanner. It is used in the yylex macro.
Referenced by parse_stream.
map< string, token_type > CPSGrader::STLDriver::reserved
Reserved words for STL parser
Referenced by CPSGrader::Scanner::Scanner.
CPSGrader::STLDriver::STLDriver()
CONSTRUCTORS.
construct a new parser driver context
CPSGrader::STLDriver::STLDriver(trace_data _trace)
construct a parser driver with data
References data.
CPSGrader::STLDriver::~STLDriver()
void CPSGrader::STLDriver::add_trace_test(const string &test_id, const string &trace_cfg, double sim_time, bool visu)
Create a new trace_tests structure and add it to the queue
References CPSGrader::trace_test::env, CPSGrader::trace_test::id, CPSGrader::trace_test::sim_time, trace_test_queue, CPSGrader::trace_test::visu.
Referenced by CPSGrader::Parser::parse.
void CPSGrader::STLDriver::add_stl_test(const string &test_id)
adds an stl_test from the stl_test_map to the current trace_test with the local params value does nothing if the stl_test does not exist Note: test inserted in the stl_test_map have no local parameters
References nb_test_total, stl_test_map, trace_test_queue.
Referenced by CPSGrader::Parser::parse.
void CPSGrader::STLDriver::add_stl_test(const string &test_id, const map< string, double > &local_param_map)
References nb_test_total, stl_test_map, trace_test_queue.
void CPSGrader::STLDriver::add_stl_test(const string &test_id, const map< string, double > &local_param_map, transducer *formula, const string &report_pos, const string &report_neg, bool is_err)
adds an stl_test to the current trace_tests - does nothing if the queue is empty
References CPSGrader::transducer::clone, nb_test_total, stl_test_map, trace_test_queue.
bool CPSGrader::STLDriver::parse_stream(std::istream &in, const std::string &sname="stream input")
PARSER.
Invoke the scanner and parser for a stream. in input stream sname stream name for error messages true if successfully parsed
References lexer, CPSGrader::Parser::parse, CPSGrader::Scanner::set_debug, CPSGrader::Parser::set_debug_level, streamname, trace_parsing, trace_scanning.
Referenced by main, parse_file, parse_string.
bool CPSGrader::STLDriver::parse_string(const std::string &input, const std::string &sname="string stream")
Invoke the scanner and parser on an input string. input input string sname stream name for error messages true if successfully parsed
References parse_stream.
Referenced by mdlStart, mexFunction, test_formula.
bool CPSGrader::STLDriver::parse_file(const std::string &filename)
Invoke the scanner and parser on a file. Use parse_stream with a std::ifstream if detection of file reading errors is required. filename input file name true if successfully parsed
References parse_stream.
void CPSGrader::STLDriver::error(const class location &l, const std::string &m)
Error handling with associated line number. This can be modified to output the error e.g. to a dialog box.
void CPSGrader::STLDriver::error(const std::string &m)
General error handling. This can be modified to output the error e.g. to a dialog box.
bool CPSGrader::STLDriver::run_tests()
API.
runs the tests of the front of trace_tests_queue and pop them assumes that data has been filled with the appropriate trace data run all stl tests for the next trace_test and write results in report
References CPSGrader::transducer::compute_robustness, d_to_s, data, error_flag, get_next_formula, get_next_stl_test, CPSGrader::transducer::init_horizon, CPSGrader::stl_test::is_error, nb_test_pos, report, CPSGrader::stl_test::report_negative, CPSGrader::stl_test::report_positive, CPSGrader::stl_test::test_id, test_log, CPSGrader::transducer::trace_data_ptr, trace_test_queue.
Referenced by run_next_trace_test.
double CPSGrader::STLDriver::test_formula(const string &)
monitor a single formula requires data is not empty
References CPSGrader::transducer::compute_robustness, data, formula_map, CPSGrader::transducer::init_horizon, parse_string, CPSGrader::transducer::trace_data_ptr.
transducer* CPSGrader::STLDriver::get_next_formula() const
gets next formula to test
References trace_test_queue.
Referenced by clear, run_tests.
const stl_test* CPSGrader::STLDriver::get_next_stl_test() const
References trace_test_queue.
Referenced by run_tests.
const trace_test* CPSGrader::STLDriver::get_next_trace_test() const
References trace_test_queue.
Referenced by main.
const bool CPSGrader::STLDriver::trace_test_queue_empty()
References trace_test_queue.
Referenced by get_next_trace_test_env, main, pop_next_trace_test.
const string CPSGrader::STLDriver::get_next_trace_test_env()
References trace_test_queue, trace_test_queue_empty.
Referenced by main.
void CPSGrader::STLDriver::pop_next_trace_test()
References trace_test_queue, trace_test_queue_empty.
Referenced by main.
void CPSGrader::STLDriver::run_next_trace_test()
References run_tests.
Referenced by main.
void CPSGrader::STLDriver::clear()
UTILITY FUNCTIONS.
clear assigned formulas and trace_test_queue
References error_flag, formula_map, get_next_formula, nb_test_pos, nb_test_total, param_map, report, stl_test_map, test_log, trace_test_queue.
void CPSGrader::STLDriver::print(ostream &out) const
Prints driver to stream output
References formula_map, param_map, trace_test_queue.
Referenced by main.
void CPSGrader::STLDriver::print() const
Prints driver to standard output
References print.
Referenced by print.
bool CPSGrader::STLDriver::read_trace_file(string trace_file_name)
Read a trace file
References data, read_trace.
Referenced by main.
void CPSGrader::STLDriver::dump()
dump all assigned formulas satisfaction function to a file compute robustness for all formulas defined in the driver and write results in files
References data, formula_map.
void CPSGrader::STLDriver::dump_trace_file(const string &)
References data.
bool CPSGrader::STLDriver::dump_test_log_file(const string &)
References nb_test_pos, nb_test_total, test_log.
void CPSGrader::STLDriver::print_trace(ostream &os)
References data.
void CPSGrader::STLDriver::print_trace()