tools.cpp
double random_double()
Referenced by rand_trace_data.
trace_data rand_trace_data(int m, int n)
Returns a m x n random trace
References random_double.
Referenced by main.
const std::string current_date_time()
void print(const trace_data &data)
Referenced by CPSGrader::not_transducer::print, CPSGrader::and_transducer::print, CPSGrader::or_transducer::print, CPSGrader::implies_transducer::print, CPSGrader::ev_transducer::print, CPSGrader::alw_transducer::print, CPSGrader::until_transducer::print, CPSGrader::stl_atom::print.
bool read_trace(const string &trace_file_name, vector< vector< double > > &data)
Referenced by CPSGrader::STLDriver::read_trace_file.