tools.h
typedef vector<vector<double> > trace_data
bool s_to_d(std::string const &s, double &x)
string to double conversion
Referenced by CPSGrader::constant_transducer::constant_transducer, CPSGrader::interval::interval, CPSGrader::Parser::parse.
string d_to_s(double const &x)
double to string conversion
Referenced by CPSGrader::STLDriver::run_tests.
trace_data rand_trace_data(int m, int n)
Returns a m x n random trace
References random_double.
Referenced by main.
const std::string current_date_time()
void print(const trace_data &)
Referenced by CPSGrader::not_transducer::print, CPSGrader::and_transducer::print, CPSGrader::or_transducer::print, CPSGrader::implies_transducer::print, CPSGrader::ev_transducer::print, CPSGrader::alw_transducer::print, CPSGrader::until_transducer::print, CPSGrader::stl_atom::print.
bool read_trace(const string &trace_file_name, trace_data &data)
Referenced by main, CPSGrader::STLDriver::read_trace_file.